version: '3.8'

services:
  postgres:
    image: postgres:14.9-alpine3.18
    container_name: xchains_testing_postgres
    environment:
      POSTGRES_DB: xchains_testing_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5473:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:

